version: "3.5"
services:
  postgres_db:
    container_name: 'postgres_db'
    image: postgres
    env_file: .env
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
#      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend_api:
    container_name: 'backend'
    build:
      context: ./code/
    env_file:
      - .env
    ports:
      - '8829:8829'

#  pgadmin:
#    container_name: 'pqadmin'
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - '5050:80'


volumes:
  postgres_db_vol:
